# Generated by Django 6.0.5 on 2026-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('s', 'simple'), ('d', 'doble'), ('F', 'familiar'), ('pv', 'suite')], max_length=10)),
            ],
        ),
    ]
