# Generated by Django 6.0.6 on 2026-06-24 00:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo 10 caracteres numericos.', regex='^\\d{1,10}$')])),
                ('nombres', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('apellidos', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de celular debe tener 10 dígitos y empezar con 09.', regex='^09\\d{8}$')])),
            ],
        ),
        migrations.RenameField(
            model_name='habitat',
            old_name='number',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='habitat',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Completada', 'Completada (Check-out)')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.habitat')),
            ],
        ),
    ]
