# Generated by Django 6.0.6 on 2026-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_cliente_rename_number_habitat_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='tipo',
            field=models.CharField(choices=[('s', 'simple'), ('d', 'doble'), ('f', 'familiar'), ('pv', 'suite')], max_length=10),
        ),
    ]
